/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * radioView.java
 *
 * Created on 2010-04-09, 13:26:12
 */

package ftimsradio;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JToggleButton;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Kamil Zygmuntowicz
 */
public class RadioView extends javax.swing.JFrame {

    /** Creates new form radioView */
    public RadioView() {
        initComponents();

        setLocation(100, 100);
        setTitle("Ftims Radio");
        setResizable(false);
    }

    // <editor-fold defaultstate="collapsed" desc="getters">
    public JToggleButton getPowerButton() {
        return powerButton;
    }

    public JButton getNextButton() {
        return nextButton;
    }

    public JButton getPrevButton() {
        return prevButton;
    }

    public JButton getSaveButton() {
        return saveButton;
    }

    public JButton getSettingsButton() {
        return settingsButton;
    }

    public JButton getStationButton1() {
        return stationButton1;
    }

    public JButton getStationButton2() {
        return stationButton2;
    }

    public JButton getStationButton3() {
        return stationButton3;
    }

    public JButton getStationButton4() {
        return stationButton4;
    }

    public JButton getStationButton5() {
        return stationButton5;
    }

    public JButton getStationButton6() {
        return stationButton6;
    }

    public JLabel getScreenText() {
        return screenText;
    }

    public JSlider getFrequencySlider() {
        return frequencySlider;
    }

    public JSlider getVolumeSlider() {
        return volumeSlider;
    }

    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="function buttons action listeners">
    //the function buttons
    void addSaveButtonListener(ActionListener sav) {
        saveButton.addActionListener(sav);
    }

    void addPowerButtonListener(ActionListener pow) {
        powerButton.addActionListener(pow);
    }

    void addNextButtonListener(ActionListener pow) {
        nextButton.addActionListener(pow);
    }

    void addPrevButtonListener(ActionListener pow) {
        prevButton.addActionListener(pow);
    }

    void addSettingsButtonListener(ActionListener pow) {
        settingsButton.addActionListener(pow);
    }

    void addAboutButtonListener(ActionListener pow) {
        aboutButton.addActionListener(pow);
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="sliders change listeners">
    void addVolumeSliderChangeListener(ChangeListener pow) {
        volumeSlider.addChangeListener(pow);
    }

    void addfrequencySliderChangeListener(ChangeListener pow) {
        frequencySlider.addChangeListener(pow);
    }// </editor-fold>

    //station buttons: I couldn't find a sophisticated solution for applying AL
    //to multiple buttons at once
    void addStationButtonListeners(ActionListener pow) {
        stationButton1.addActionListener(pow);
        stationButton2.addActionListener(pow);
        stationButton3.addActionListener(pow);
        stationButton4.addActionListener(pow);
        stationButton5.addActionListener(pow);
        stationButton6.addActionListener(pow);
    }

    //this function is quite obvious, if the radio is turned off
    //some buttons become disabled
    public void setFunctionButtonsVisibility(Boolean powerOn){
        //I decided that settings and about buttons will work
        //undependently from power

        stationButton1.setEnabled(powerOn);
        stationButton2.setEnabled(powerOn);
        stationButton3.setEnabled(powerOn);
        stationButton4.setEnabled(powerOn);
        stationButton5.setEnabled(powerOn);
        stationButton6.setEnabled(powerOn);

        saveButton.setEnabled(powerOn);
        nextButton.setEnabled(powerOn);
        prevButton.setEnabled(powerOn);

        volumeSlider.setEnabled(powerOn);
        frequencySlider.setEnabled(powerOn);

        menuStationNext.setEnabled(powerOn);
        menuStationPrev.setEnabled(powerOn);
        menuStationSave.setEnabled(powerOn);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slidersPanel = new javax.swing.JPanel();
        volumeLabel = new javax.swing.JLabel();
        frequencyLabel = new javax.swing.JLabel();
        volumeSlider = new javax.swing.JSlider();
        frequencySlider = new javax.swing.JSlider();
        funcButtonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        powerButton = new javax.swing.JToggleButton();
        stationsPanel = new javax.swing.JPanel();
        stationButton1 = new javax.swing.JButton();
        stationButton2 = new javax.swing.JButton();
        stationButton3 = new javax.swing.JButton();
        stationButton4 = new javax.swing.JButton();
        stationButton5 = new javax.swing.JButton();
        stationButton6 = new javax.swing.JButton();
        radioScreen = new javax.swing.JPanel();
        screenText = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuSettings = new javax.swing.JMenu();
        menuStations = new javax.swing.JMenu();
        menuStationNext = new javax.swing.JMenuItem();
        menuStationPrev = new javax.swing.JMenuItem();
        menuStationSave = new javax.swing.JMenuItem();
        menuStationList = new javax.swing.JMenuItem();
        menuDBase = new javax.swing.JMenu();
        menuDBaseLoad = new javax.swing.JMenuItem();
        menuDBaseSave = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        slidersPanel.setName("slidersPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ftimsradio.FtimsRadioApp.class).getContext().getResourceMap(RadioView.class);
        volumeLabel.setText(resourceMap.getString("volumeLabel.text")); // NOI18N
        volumeLabel.setName("volumeLabel"); // NOI18N

        frequencyLabel.setText(resourceMap.getString("frequencyLabel.text")); // NOI18N
        frequencyLabel.setName("frequencyLabel"); // NOI18N

        volumeSlider.setName("volumeSlider"); // NOI18N

        frequencySlider.setName("frequencySlider"); // NOI18N

        javax.swing.GroupLayout slidersPanelLayout = new javax.swing.GroupLayout(slidersPanel);
        slidersPanel.setLayout(slidersPanelLayout);
        slidersPanelLayout.setHorizontalGroup(
            slidersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slidersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(slidersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slidersPanelLayout.createSequentialGroup()
                        .addComponent(volumeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(slidersPanelLayout.createSequentialGroup()
                        .addComponent(frequencyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frequencySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        slidersPanelLayout.setVerticalGroup(
            slidersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slidersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(slidersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(volumeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(slidersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(frequencyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frequencySlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        funcButtonPanel.setName("funcButtonPanel"); // NOI18N

        saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
        saveButton.setName("saveButton"); // NOI18N

        nextButton.setText(resourceMap.getString("nextButton.text")); // NOI18N
        nextButton.setName("nextButton"); // NOI18N

        prevButton.setText(resourceMap.getString("prevButton.text")); // NOI18N
        prevButton.setName("prevButton"); // NOI18N

        settingsButton.setText(resourceMap.getString("settingsButton.text")); // NOI18N
        settingsButton.setName("settingsButton"); // NOI18N

        aboutButton.setText(resourceMap.getString("aboutButton.text")); // NOI18N
        aboutButton.setName("aboutButton"); // NOI18N

        powerButton.setText(resourceMap.getString("powerButton.text")); // NOI18N
        powerButton.setName("powerButton"); // NOI18N

        javax.swing.GroupLayout funcButtonPanelLayout = new javax.swing.GroupLayout(funcButtonPanel);
        funcButtonPanel.setLayout(funcButtonPanelLayout);
        funcButtonPanelLayout.setHorizontalGroup(
            funcButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funcButtonPanelLayout.createSequentialGroup()
                .addGroup(funcButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(powerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funcButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prevButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funcButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        funcButtonPanelLayout.setVerticalGroup(
            funcButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funcButtonPanelLayout.createSequentialGroup()
                .addGroup(funcButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(powerButton)
                    .addComponent(nextButton)
                    .addComponent(settingsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funcButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(prevButton)
                    .addComponent(aboutButton)))
        );

        stationsPanel.setName("stationsPanel"); // NOI18N

        stationButton1.setText(resourceMap.getString("stationButton1.text")); // NOI18N
        stationButton1.setName("stationButton1"); // NOI18N

        stationButton2.setText(resourceMap.getString("stationButton2.text")); // NOI18N
        stationButton2.setName("stationButton2"); // NOI18N

        stationButton3.setText(resourceMap.getString("stationButton3.text")); // NOI18N
        stationButton3.setName("stationButton3"); // NOI18N

        stationButton4.setText(resourceMap.getString("stationButton4.text")); // NOI18N
        stationButton4.setName("stationButton4"); // NOI18N

        stationButton5.setText(resourceMap.getString("stationButton5.text")); // NOI18N
        stationButton5.setName("stationButton5"); // NOI18N

        stationButton6.setText(resourceMap.getString("stationButton6.text")); // NOI18N
        stationButton6.setName("stationButton6"); // NOI18N

        javax.swing.GroupLayout stationsPanelLayout = new javax.swing.GroupLayout(stationsPanel);
        stationsPanel.setLayout(stationsPanelLayout);
        stationsPanelLayout.setHorizontalGroup(
            stationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stationsPanelLayout.createSequentialGroup()
                .addComponent(stationButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stationButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stationButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stationButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stationButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stationButton6))
        );
        stationsPanelLayout.setVerticalGroup(
            stationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(stationButton1)
                .addComponent(stationButton2)
                .addComponent(stationButton3)
                .addComponent(stationButton4)
                .addComponent(stationButton5)
                .addComponent(stationButton6))
        );

        radioScreen.setBackground(resourceMap.getColor("radioScreen.background")); // NOI18N
        radioScreen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        radioScreen.setName("radioScreen"); // NOI18N

        screenText.setFont(resourceMap.getFont("screenText.font")); // NOI18N
        screenText.setForeground(resourceMap.getColor("screenText.foreground")); // NOI18N
        screenText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        screenText.setText(resourceMap.getString("screenText.text")); // NOI18N
        screenText.setName("screenText"); // NOI18N

        javax.swing.GroupLayout radioScreenLayout = new javax.swing.GroupLayout(radioScreen);
        radioScreen.setLayout(radioScreenLayout);
        radioScreenLayout.setHorizontalGroup(
            radioScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screenText, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        radioScreenLayout.setVerticalGroup(
            radioScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screenText, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setName("menuBar"); // NOI18N

        menuSettings.setText(resourceMap.getString("menuSettings.text")); // NOI18N
        menuSettings.setName("menuSettings"); // NOI18N
        menuBar.add(menuSettings);

        menuStations.setText(resourceMap.getString("menuStations.text")); // NOI18N
        menuStations.setName("menuStations"); // NOI18N

        menuStationNext.setText(resourceMap.getString("menuStationNext.text")); // NOI18N
        menuStationNext.setName("menuStationNext"); // NOI18N
        menuStations.add(menuStationNext);

        menuStationPrev.setText(resourceMap.getString("menuStationPrev.text")); // NOI18N
        menuStationPrev.setName("menuStationPrev"); // NOI18N
        menuStations.add(menuStationPrev);

        menuStationSave.setText(resourceMap.getString("menuStationSave.text")); // NOI18N
        menuStationSave.setName("menuStationSave"); // NOI18N
        menuStations.add(menuStationSave);

        menuStationList.setText(resourceMap.getString("menuStationList.text")); // NOI18N
        menuStationList.setName("menuStationList"); // NOI18N
        menuStations.add(menuStationList);

        menuBar.add(menuStations);

        menuDBase.setText(resourceMap.getString("menuDBase.text")); // NOI18N
        menuDBase.setName("menuDBase"); // NOI18N

        menuDBaseLoad.setText(resourceMap.getString("menuDBaseLoad.text")); // NOI18N
        menuDBaseLoad.setName("menuDBaseLoad"); // NOI18N
        menuDBase.add(menuDBaseLoad);

        menuDBaseSave.setText(resourceMap.getString("menuDBaseSave.text")); // NOI18N
        menuDBaseSave.setName("menuDBaseSave"); // NOI18N
        menuDBase.add(menuDBaseSave);

        menuBar.add(menuDBase);

        menuAbout.setText(resourceMap.getString("menuAbout.text")); // NOI18N
        menuAbout.setName("menuAbout"); // NOI18N
        menuBar.add(menuAbout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slidersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funcButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(radioScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(slidersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(funcButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JLabel frequencyLabel;
    private javax.swing.JSlider frequencySlider;
    private javax.swing.JPanel funcButtonPanel;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDBase;
    private javax.swing.JMenuItem menuDBaseLoad;
    private javax.swing.JMenuItem menuDBaseSave;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JMenuItem menuStationList;
    private javax.swing.JMenuItem menuStationNext;
    private javax.swing.JMenuItem menuStationPrev;
    private javax.swing.JMenuItem menuStationSave;
    private javax.swing.JMenu menuStations;
    private javax.swing.JButton nextButton;
    private javax.swing.JToggleButton powerButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JPanel radioScreen;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel screenText;
    private javax.swing.JButton settingsButton;
    private javax.swing.JPanel slidersPanel;
    private javax.swing.JButton stationButton1;
    private javax.swing.JButton stationButton2;
    private javax.swing.JButton stationButton3;
    private javax.swing.JButton stationButton4;
    private javax.swing.JButton stationButton5;
    private javax.swing.JButton stationButton6;
    private javax.swing.JPanel stationsPanel;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables

}
